#!/bin/bash

[ -z "$*" ] && {
    ls -1 $HOME/.iexdock/docker/$1
    exit 0
}

[ "$1" == "rebuild" ] && {
    docker image rm --force $(docker images | grep ^elixir | sed -E 's/^([^ ]+).*/\1/')
    exit 0
}

docker build --build-arg UID=$UID $HOME/.iexdock/docker/$1 -t $1
